name: CI

on: 
   push:
     branches: 
       - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: echo "Step1"
     
   deploy:
   
   
   runs-on: ubuntu-latest
      
      
    steps:
      - name: step2
        run : echo "Step2"  
      
        
